let EventTypes = {};
[
  'ACL_USER_SET_USER',
  'ACL_USERS_CHANGE',
  'ACL_USERS_REQUEST_ERROR',
  'ACL_USER_CREATE_ERROR',
  'ACL_USER_CREATE_SUCCESS',
  'ACL_USER_DELETE_ERROR',
  'ACL_USER_DELETE_SUCCESS',
  'ACL_USER_DETAILS_FETCH_START',
  'ACL_USER_DETAILS_FETCHED_ERROR',
  'ACL_USER_DETAILS_FETCHED_SUCCESS',
  'ACL_USER_DETAILS_GROUPS_CHANGE',
  'ACL_USER_DETAILS_GROUPS_ERROR',
  'ACL_USER_DETAILS_PERMISSIONS_CHANGE',
  'ACL_USER_DETAILS_PERMISSIONS_ERROR',
  'ACL_USER_DETAILS_USER_CHANGE',
  'ACL_USER_DETAILS_USER_ERROR',
  'ACL_USER_UPDATE_ERROR',
  'ACL_USER_UPDATE_SUCCESS'
].forEach(function (eventType) {
  EventTypes[eventType] = eventType;
});

module.exports = EventTypes;
