let EventTypes = {};
[
  'ACL_GROUPS_CHANGE',
  'ACL_GROUPS_REQUEST_ERROR',
  'ACL_GROUP_ADD_USER_ERROR',
  'ACL_GROUP_ADD_USER_SUCCESS',
  'ACL_GROUP_CREATE_ERROR',
  'ACL_GROUP_CREATE_SUCCESS',
  'ACL_GROUP_DELETE_ERROR',
  'ACL_GROUP_DELETE_SUCCESS',
  'ACL_GROUP_DETAILS_FETCHED_ERROR',
  'ACL_GROUP_DETAILS_FETCHED_SUCCESS',
  'ACL_GROUP_DETAILS_GROUP_CHANGE',
  'ACL_GROUP_DETAILS_GROUP_ERROR',
  'ACL_GROUP_DETAILS_PERMISSIONS_CHANGE',
  'ACL_GROUP_DETAILS_PERMISSIONS_ERROR',
  'ACL_GROUP_DETAILS_USERS_CHANGE',
  'ACL_GROUP_DETAILS_USERS_ERROR',
  'ACL_GROUP_REMOVE_USER_SUCCESS',
  'ACL_GROUP_REMOVE_USER_ERROR',
  'ACL_GROUP_UPDATE_ERROR',
  'ACL_GROUP_UPDATE_SUCCESS',
  'ACL_GROUP_USERS_CHANGED'
].forEach(function (eventType) {
  EventTypes[eventType] = eventType;
});

module.exports = EventTypes;
