var ActionTypes = {
  REQUEST_MESOS_STATE: "REQUEST_MESOS_STATE",
  REQUEST_MESOS_STATE_SUCCESS: "REQUEST_MESOS_STATE_SUCCESS",
  REQUEST_MESOS_STATE_ERROR: "REQUEST_MESOS_STATE_ERROR",
  REQUEST_MARATHON_HEALTH: "REQUEST_MARATHON_HEALTH",
  REQUEST_MARATHON_HEALTH_SUCCESS: "REQUEST_MARATHON_HEALTH_SUCCESS",
  REQUEST_MARATHON_HEALTH_ERROR: "REQUEST_MARATHON_HEALTH_ERROR",
  REQUEST_SIDEBAR_CLOSE: "REQUEST_SIDEBAR_CLOSE",
  REQUEST_SIDEBAR_OPEN: "REQUEST_SIDEBAR_OPEN"
};

module.exports = ActionTypes;
