var ActionTypes = {
  REQUEST_MESOS_STATE: "REQUEST_MESOS_STATE",
  REQUEST_MESOS_STATE_SUCCESS: "REQUEST_MESOS_STATE_SUCCESS",
  REQUEST_MESOS_STATE_ERROR: "REQUEST_MESOS_STATE_ERROR",
  FILTER_SERVICES_BY_STRING: "FILTER_SERVICES_BY_STRING"
};

module.exports = ActionTypes;
