var ActionTypes = {
  REQUEST_MESOS_STATE: "REQUEST_MESOS_STATE",
  REQUEST_MESOS_STATE_SUCCESS: "REQUEST_MESOS_STATE_SUCCESS",
  REQUEST_MESOS_STATE_ERROR: "REQUEST_MESOS_STATE_ERROR",
  REQUEST_MARATHON_APPS: "REQUEST_MARATHON_APPS",
  REQUEST_MARATHON_APPS_SUCCESS: "REQUEST_MARATHON_APPS_SUCCESS",
  REQUEST_MARATHON_APPS_ERROR: "REQUEST_MARATHON_APPS_ERROR",
  REQUEST_SIDEBAR_CLOSE: "REQUEST_SIDEBAR_CLOSE",
  REQUEST_SIDEBAR_OPEN: "REQUEST_SIDEBAR_OPEN",
  SERVER_ACTION: "SERVER_ACTION",
  SIDEBAR_ACTION: "SIDEBAR_ACTION"
};

module.exports = ActionTypes;
