var EventTypes = {
  MESOS_STATE_CHANGE: "MESOS_STATE_CHANGE",
  MESOS_STATE_REQUEST_ERROR: "MESOS_STATE_REQUEST_ERROR",
  MARATHON_APPS_CHANGE: "MARATHON_APPS_CHANGE",
  MARATHON_APPS_REQUEST_ERROR: "MARATHON_APPS_REQUEST_ERROR",
  SIDEBAR_CHANGE: "SIDEBAR_CHANGE",
  SHOW_CLI_INSTRUCTIONS: "SHOW_CLI_INSTRUCTIONS",
  SHOW_TOUR: "SHOW_TOUR",
  SHOW_INTERCOM: "SHOW_INTERCOM"
};

module.exports = EventTypes;
