var EventTypes = {
  DCOS_METADATA_CHANGE: "DCOS_METADATA_CHANGE",
  INTERCOM_CHANGE: "INTERCOM_CHANGE",
  MESOS_SUMMARY_CHANGE: "MESOS_SUMMARY_CHANGE",
  MESOS_SUMMARY_REQUEST_ERROR: "MESOS_SUMMARY_REQUEST_ERROR",
  MESOS_STATE_CHANGE: "MESOS_STATE_CHANGE",
  MESOS_STATE_REQUEST_ERROR: "MESOS_STATE_REQUEST_ERROR",
  METADATA_CHANGE: "METADATA_CHANGE",
  MARATHON_APPS_CHANGE: "MARATHON_APPS_CHANGE",
  MARATHON_APPS_ERROR: "MARATHON_APPS_ERROR",
  SIDEBAR_CHANGE: "SIDEBAR_CHANGE",
  SHOW_CLI_INSTRUCTIONS: "SHOW_CLI_INSTRUCTIONS",
  SHOW_TOUR: "SHOW_TOUR",
  SHOW_VERSIONS_SUCCESS: "SHOW_VERSIONS_SUCCESS",
  SHOW_VERSIONS_ERROR: "SHOW_VERSIONS_ERROR",
  TASK_DIRECTORY_CHANGE: "TASK_DIRECTORY_CHANGE",
  TASK_DIRECTORY_ERROR: "TASK_DIRECTORY_ERROR",
  CONFIG_LOADED: "CONFIG_LOADED",
  CONFIG_ERROR: "CONFIG_ERROR",
  PLUGINS_CONFIGURED: "PLUGINS_CONFIGURED"
};

module.exports = EventTypes;
