var EventTypes = {
  INTERCOM_CHANGE: "INTERCOM_CHANGE",
  MESOS_SUMMARY_CHANGE: "MESOS_SUMMARY_CHANGE",
  MESOS_STATE_REQUEST_ERROR: "MESOS_STATE_REQUEST_ERROR",
  MARATHON_APPS_CHANGE: "MARATHON_APPS_CHANGE",
  MARATHON_APPS_REQUEST_ERROR: "MARATHON_APPS_REQUEST_ERROR",
  SIDEBAR_CHANGE: "SIDEBAR_CHANGE",
  SHOW_CLI_INSTRUCTIONS: "SHOW_CLI_INSTRUCTIONS",
  SHOW_TOUR: "SHOW_TOUR",
  SHOW_VERSIONS_SUCCESS: "SHOW_VERSIONS_SUCCESS",
  SHOW_VERSIONS_ERROR: "SHOW_VERSIONS_ERROR"
};

module.exports = EventTypes;
