let EventTypes = {};
[
  'ACL_CREATE_ERROR',
  'ACL_CREATE_SUCCESS',
  'ACL_GROUP_GRANT_ACTION_CHANGE',
  'ACL_GROUP_GRANT_ACTION_ERROR',
  'ACL_GROUP_REVOKE_ACTION_CHANGE',
  'ACL_GROUP_REVOKE_ACTION_ERROR',
  'ACL_RESOURCE_ACLS_CHANGE',
  'ACL_RESOURCE_ACLS_ERROR',
  'ACL_USER_GRANT_ACTION_CHANGE',
  'ACL_USER_GRANT_ACTION_ERROR',
  'ACL_USER_REVOKE_ACTION_CHANGE',
  'ACL_USER_REVOKE_ACTION_ERROR'
].forEach(function (eventType) {
  EventTypes[eventType] = eventType;
});

module.exports = EventTypes;
