let ActionTypes = {};
[
  'REQUEST_NETWORKING_BACKEND_CONNECTIONS_ERROR',
  'REQUEST_NETWORKING_BACKEND_CONNECTIONS_SUCCESS',
  'REQUEST_NETWORKING_NODE_MEMBERSHIPS_ERROR',
  'REQUEST_NETWORKING_NODE_MEMBERSHIPS_SUCCESS',
  'REQUEST_NETWORKING_VIP_DETAIL_ERROR',
  'REQUEST_NETWORKING_VIP_DETAIL_SUCCESS',
  'REQUEST_NETWORKING_VIPS_ERROR',
  'REQUEST_NETWORKING_VIPS_SUCCESS'
].forEach(function (actionType) {
  ActionTypes[actionType] = actionType;
});

module.exports = ActionTypes;
