let EventTypes = {};
[
  'NETWORKING_BACKEND_CONNECTIONS_CHANGE',
  'NETWORKING_BACKEND_CONNECTIONS_REQUEST_ERROR',
  'NETWORKING_NODE_MEMBERSHIP_CHANGE',
  'NETWORKING_NODE_MEMBERSHIP_REQUEST_ERROR',
  'NETWORKING_VIP_DETAIL_CHANGE',
  'NETWORKING_VIP_DETAIL_REQUEST_ERROR',
  'NETWORKING_VIPS_CHANGE',
  'NETWORKING_VIPS_REQUEST_ERROR'
].forEach(function (eventType) {
  EventTypes[eventType] = eventType;
});

module.exports = EventTypes;
