#!/usr/bin/env bash
# Prepares for community edition build

EMPTY_OBJ_EXPORT="export default {};";
EMPTY_REACT_EXPORT="/*eslint-disable no-unused-vars*/
import React from \"react\";
/*eslint-enable no-unused-vars*/
export default class extends React.Component {
  render() {
    return null;
  }
}
";

# Remove schemas
rm -rf ./schema/acl

# ./test files
rm -rf ./tests/_fixtures/acl
rm ./tests/Settings*
rm ./tests/User*
# rm ./tests/Group*

# Components
rm ./src/js/components/__tests__/Group*
echo "$EMPTY_REACT_EXPORT" > ./src/js/components/GroupFormModal.js
echo "$EMPTY_REACT_EXPORT" > ./src/js/components/GroupSidePanelContents.js
echo "$EMPTY_REACT_EXPORT" > ./src/js/components/GroupUserTable.js
rm ./src/js/components/__tests__/Permissions*
echo "$EMPTY_REACT_EXPORT" > ./src/js/components/PermissionsTable.js
echo "$EMPTY_REACT_EXPORT" > ./src/js/components/PermissionsView.js
rm ./src/js/components/__tests__/User*
echo "$EMPTY_REACT_EXPORT" > ./src/js/components/UserDetails.js
echo "$EMPTY_REACT_EXPORT" > ./src/js/components/UserFormModal.js
echo "$EMPTY_REACT_EXPORT" > ./src/js/components/UserGroupMembershipTab.js
echo "$EMPTY_REACT_EXPORT" > ./src/js/components/UserGroupTable.js
echo "$EMPTY_REACT_EXPORT" > ./src/js/components/UserSidePanel.js
echo "$EMPTY_REACT_EXPORT" > ./src/js/components/UserSidePanelContents.js

# Events
rm ./src/js/events/__tests__/ACL*
rm ./src/js/events/ACL*

# Pages
echo "$EMPTY_REACT_EXPORT" > ./src/js/pages/SettingsPage.js
echo "$EMPTY_REACT_EXPORT" > ./src/js/pages/settings/OrganizationTab.js
echo "$EMPTY_REACT_EXPORT" > ./src/js/pages/settings/OverviewTab.js
echo "$EMPTY_REACT_EXPORT" > ./src/js/pages/settings/UsersTab.js
echo "$EMPTY_REACT_EXPORT" > ./src/js/pages/settings/GroupsTab.js

# Plugins
# echo $EMPTY_REACT_EXPORT > ./src/js/plugins/Authentication*

# Stores
rm ./src/js/stores/__tests__/ACL*
echo $EMPTY_OBJ_EXPORT > ./src/js/stores/ACLStore.js
echo $EMPTY_OBJ_EXPORT > ./src/js/stores/ACLGroupsStore.js
echo $EMPTY_OBJ_EXPORT > ./src/js/stores/ACLGroupStore.js
echo $EMPTY_OBJ_EXPORT > ./src/js/stores/ACLUsersStore.js
echo $EMPTY_OBJ_EXPORT > ./src/js/stores/ACLUserStore.js

# Structs
rm ./src/js/structs/__tests__/ACL*
rm ./src/js/structs/ACL*
rm ./src/js/structs/__tests__/Group*
rm ./src/js/structs/Group*
rm ./src/js/structs/__tests__/User*
rm ./src/js/structs/User*
