 #%RAML 0.8
title: Component Health Checks API Spec
version: v1
baseUri: /api/{version}/system/health
mediaType: application/json
schemas:
  - components: !include ../../schema/component-health/components.json
  - component: !include ../../schema/component-health/component.json
  - nodes: !include ../../schema/component-health/nodes.json
  - node: !include ../../schema/component-health/node.json
  - report: !include ../../schema/component-health/report.json

/components:
  displayName: Components Health
  get:
    description: Get a list of components and their health status.
    responses:
      200:
        description: Successful response.
        body:
          application/json:
            schema: components
            example: |
              {
                "array": [
                  {
                    "component_id": "marathon_service", # Is the component family
                    "component_description": "marathon service",
                    "component_health": 0,
                    "component_check_output": "OK"
                  },
                  {
                    "component_id": "mesos_dns_service",
                    "component_description": "Mesos DNS",
                    "component_health": 1,
                    "component_check_output": "Mesos Dns Service failed to start on host ip-10.0.0.1. Please see `systemctl -u mesos-dns.service` for more information"
                  },
                  {
                    "component_id": "mesos_master_service",
                    "component_description": "mesos master service",
                    "component_health": 0,
                    "component_check_output": "OK"
                  },
                  {
                    "component_id": "nginx_service",
                    "component_description": "nginx service",
                    "component_health": 0,
                    "component_check_output": "OK"
                  }
                ]
              }

  /{component-id}:
    uriParameters:
      component-id:
        description: Requested component.
        type: string
    displayName: Component Health
    get:
      description: Get the component health summaries by node_id.
      responses:
        200:
          description: Successful response.
          body:
            application/json:
              schema: component
              example: |
                # Example query for nginx_service in a 3-master cluster would return the component
                # health on the 3 masters on which that component runs.
                {
                  "component_id": "mesos_dns_service",
                  "component_description": "Mesos DNS",
                  "component_health": 1,
                  "component_check_output": "Mesos Dns Service failed to start on host ip-10.0.0.1. Please see `systemctl -u mesos-dns.service` for more information"
                }

    /nodes:
      displayName: Component Nodes Health
      get:
        description: Get a list of the components node health summaries.
        responses:
          200:
            description: Successful response.
            body:
              application/json:
                schema: nodes
                example: |
                  # Example response from a 2-node cluster where one node has components with health > 0
                  {
                    "array": [
                      {
                        "node_id": "ip-10-10-0-235",
                        "node_role": "master",
                        "node_health": 0
                      },
                      {
                        "node_id": "ip-10-10-0-236",
                        "node_role": "agent",
                        "node_health": 1
                      }
                    ]
                  }
      # Must ensure all node_id's contain are hyphened and not "." separated. Only matters if we go
      # through a proxy of some sort, but generally not great to "." separate in our URL requested.
      /{node-id}:
        uriParameters:
          node-id:
            description: Requested node.
            type: string
        displayName: Node Health
        get:
          description: Get node health status.
          responses:
            200:
              description: Successful response.
              body:
                application/json:
                  schema: node
                  example: |
                    # Example response from a healthy node with all components == 0
                    {
                      "node_id": "ip-10-10-0-236",
                      "node_role": "agent",
                      "node_health": 1,
                      "component_check_output": "Mesos Dns Service failed to start on host ip-10.0.0.1. Please see `systemctl -u mesos-dns.service` for more information"
                    }

# This is possibly just a 301 -> /nodes, lets disucss.
/report:
  displayName: Health Report
  get:
    description: Get a full report of components' health.
    responses:
      200:
        description: Successful response.
        headers:
          Content-Disposition:
            type: string
            required: true
            example: |
              Content-Disposition:
              attachment; filename="report.txt"
